### ISSUE TITLE
ERROR when run hugo comand

### ISSUE THREAD

**Issue by dz0ne** [themefisher/bigspring-hugo-startup-theme#11]
when i run 
sudo hugo 
the output is ; 
Total in 0 ms
Error: module "bigspring" not found; either add it as a Hugo Module or store it in "/home/fouad/Downloads/bigspring-hugo-startup-theme-master/exampleSite/themes".: module does not exist

**Comment by somratpro** [comment]
Hello @dz0ne 

Please follow this doc https://docs.gethugothemes.com/guide/#run-theme-locally

**Comment by gitgyan-web** [comment]
run this command 
**hugo server --themesDir ../..**
instead of
**hugo server**

**Comment by somratpro** [comment]
I am going to close this issue, if you have more queries, feel free to create a new issue. thanks for being with themefisher.

**Comment by CaoHuy26** [comment]
@dz0ne 

Rename folder ```bigspring-hugo-startup-theme-master``` to ```bigspring```.
