### ISSUE TITLE
New post cannot be added

### ISSUE THREAD

**Issue by gitgyan-web** [themefisher/bigspring-hugo-startup-theme#12]
hugo new blog/new-post.md

cannot be added in localhost

Error: module "bigspring" not found; either add it as a Hugo Module or store it in "C:\\Hugo\\Sites\\bigspring\\exampleSite\\themes".: module does not exist

**Comment by somratpro** [comment]
Hello @gitgyan-web 
Please follow this doc https://docs.gethugothemes.com/guide/#run-theme-locally

**Comment by gitgyan-web** [comment]
thank you for the response,
I am following the same steps form the starts, but could not add a new post from the command line(now I'm adding it manually )

In the image, you can see that I can run the server locally but could not add a new post.
Thank you
![hugo ex error](https://user-images.githubusercontent.com/73237061/102192915-694ab700-3ee1-11eb-8e9c-081c9011a293.JPG)

**Comment by somratpro** [comment]
Try `hugo new blog/new-post.md --themesDir ../..`

**Comment by gitgyan-web** [comment]
yep this works, thank you dude 👍
