### ISSUE TITLE
Firebase Deployment Error

### ISSUE THREAD

**Issue by skaftanis** [themefisher/bigspring-hugo-startup-theme#13]
Hi, 
There is a problem with bigspring and Firebase hosting. 
The home page looks ok, but all the other pages are without css loaded and in the console there are the errors bellow: 

`Uncaught SyntaxError: Unexpected token '<'
slick.min.js:1 Uncaught SyntaxError: Unexpected token '<'
script.min.js:1 Uncaught TypeError: $(...).slick is not a function
    at script.min.js:1
    at script.min.js:1
(anonymous) @ script.min.js:1
(anonymous) @ script.min.js:1`

Locally everything works ok. Thanks in advance!

**Comment by somratpro** [comment]
Hello @skaftanis,

It seems you are missing the exact baseURL that firebase is providing you. make sure you have put this domain in your themes configuration baseURL. that will solve your issue I guess.

**Comment by skaftanis** [comment]
Thank you very much! That solved the issue ;)
