### ISSUE TITLE
Adding sidebar widget

### ISSUE THREAD

**Issue by gitgyan-web** [themefisher/bigspring-hugo-startup-theme#15]
I'm using this theme for weeks, I'm quite impressed with the style, options, and also support for this theme.
The only missing this is **sidebar**. I tried to combine sidebar from the **MainRoad** theme, it is working but everything else is messing up.
Is there any way I can add a custom sidebar without messing with anything?
I want to add a recent post, category, tags, etc in this widget
I really want this to work on my blog website.
Thank you

**Comment by somratpro** [comment]
Hello @gitgyan-web,
Thanks for using our theme. You can contact us for any kind of theme customization at mehedi@themefisher.com [paid], we are available now.
