### ISSUE TITLE
How to add favicon to this theme?

### ISSUE THREAD

**Issue by betterify** [themefisher/bigspring-hugo-startup-theme#19]
I am not able to get the favicon thing for this theme. I tried everything but it doesn't work. How this can be achieved? A solution is highly appreciated 😊

**Comment by betterify** [comment]
I figured it out. **And its working!!** So I am closing the issue.

**Comment by batesenergy** [comment]
Can you share with us what you did to make this work? Im having the same issue?

**Comment by somratpro** [comment]
Hello @batesenergy 

Please replace `static/images/favicon.png` with the same name. and it will be updated automatically. thank you

**Comment by betterify** [comment]
> Can you share with us what you did to make this work? Im having the same issue?

This is what I did. I replaced `/exampleSite/static/images/favicon.svg` I replaced the PNG image with SVG. I tried both. SVG is more sharper than PNG. I used Figma for the logo design. Thanks 😊
