### ISSUE TITLE
Algolia Search Help

### ISSUE THREAD

**Issue by betterify** [themefisher/bigspring-hugo-startup-theme#20]
I have created a new project with the above theme. And I have followed the complete process given in the below link to add Algolia Search to my site:

https://forestry.io/blog/search-with-algolia-in-hugo/

But the rebuild command does not generate the `algolia.json` in the root. Because of this I am not able to proceed further. The site works fime in all other aspects. **Any help please!!** Thanks.

**Comment by somratpro** [comment]
Hello @betterify 

It's nice to hear that you are using our theme. In this case, you need to contact algolia, or we can create a search functionality without algolia. it's even better. Please contact our CEO for any kind of customization at mehedi@themefisher.com [paid]
