### ISSUE TITLE
The template won't deploy to Netlify

### ISSUE THREAD

**Issue by x1337x-sec** [themefisher/bigspring-hugo-startup-theme#29]
I am a premium user and I downloaded this template edited the contents locally and uploaded it to Gitlab .

However when deploying to Forestry you don't get the config.toml file on the left side bar and the build cmd fails on Netlify.

Please advise

**Comment by somratpro** [comment]
Hello @x1337x-sec 

I just deploy this theme with netlify and don't found any issues. here is the demo link: https://bigspring-test.netlify.app/
please share your repository with me, or just fork this template and try to deploy with netlify.

**Comment by somratpro** [comment]
Hello @x1337x-sec 

I think your issue has been fixed. so I am closing this issue. if you need any help, you can open a new issue at any time. thank you
