### ISSUE TITLE
The navigation bar does not close once open when browsing from a responsive device.

### ISSUE THREAD

**Issue by angelzarazua** [themefisher/bigspring-hugo-startup-theme#35]
[
![Screenshot_59](https://user-images.githubusercontent.com/37393564/119275957-a7a97800-bbdd-11eb-9e97-d63497b8c2a0.png)
](url)

**Comment by angelzarazua** [comment]
Sorry i see they already fixed it

**Comment by mgoldchild** [comment]
I have this problem on my Android phone.

**Comment by renjithbz** [comment]
@mgoldchild did you tried the latest version?

**Comment by GaranceR** [comment]
@angelzarazua How did they fix it? I still have that problem :/

**Comment by angelzarazua** [comment]
Sorry I thought they solved the problem but following the instructions did not work. But commenting on the following line of code did work for me in the *JS Plugins + Main script* section.

The file is called `script.html` and is located at: `themes/bigspring/layouts/partials/script.html`
The line that I commented is the last one.

```html
<!-- JS Plugins + Main script -->
{{ $scripts := slice }}
{{ range site.Params.plugins.js}}
{{ if findRE "^http" .link }}
<script src="{{ .link | absURL }}" type="application/javascript" {{.attributes | safeHTMLAttr}}></script>
{{ else }}
{{ $scripts = $scripts | append (resources.Get .link) }}
{{ end }}
{{ end }}
{{ $scripts := $scripts | append (resources.Get "js/script.js" | minify) }}
{{ $scripts := $scripts | resources.Concat "/js/script.js" | minify | fingerprint "sha512" }}
<!-- <script crossorigin="anonymous" defer="defer" data-turbolinks-suppress-warning integrity="{{ $scripts.Data.Integrity }}" type="application/javascript">{{$scripts.Content | safeJS}}</script> -->
```

**Comment by somratpro** [comment]
Hello there, 

This issue has been fixed. please download the latest code. thank you
