### ISSUE TITLE
List page

### ISSUE THREAD

**Issue by zhironwu** [themefisher/bigspring-hugo-startup-theme#40]
I'm new to Hugo (and code in general) and I can't figure out how to create list pages (like "Blog" in the demo). Sure, I can use exampleSite and edit it but I want to have more than one list page. Neither creating _index.md nor going to the subfolder directory result in a list page.

**Comment by tfsomrat** [comment]
Hello @zhironwu 

Thanks for using our theme, this doc should help https://docs.gethugothemes.com/guide/#maintain-page

**Comment by zhironwu** [comment]
Hi!
I figured it out by adding `(eq .Section "name")` to list.html in the layout folder. Thanks for the help! I'll close this issue.
