### ISSUE TITLE
How can I change the default language?

### ISSUE THREAD

**Issue by iucvcom** [themefisher/bigspring-hugo-startup-theme#41]
I want to set other languages as the default language instead of English. What should I do?

**Comment by tfsomrat** [comment]
Hello @iucvcom 

Please follow this official Hugo Docs https://gohugo.io/content-management/multilingual/

**Comment by eteitelbaum** [comment]
Hi, in relation to this, where is `defaultContentLanguage: en`? I do not see this line in `config.yaml` in the `config\_default` folder.

**Comment by mehedi-sharif** [comment]
Hello @eteitelbaum 
This is not available in the file right now, but you can add it at the top of the `config.toml`. and it will work. thank you

**Comment by eteitelbaum** [comment]
Thanks, what if I just want to set the language to English and get rid of the toggle between English and German (all the way on the top right menu)? Is there a way to do that? I tried clearing out `languages.toml` but then the site won't compile.  I really just want to get rid of that toggle button (EN/DE).

**Comment by mehedi-sharif** [comment]
You can disable `de` language, then your multilingual will automatically turn off. here is how you can do it https://gohugo.io/content-management/multilingual/#disable-a-language
