### ISSUE TITLE
{{ with site.Params.variables }} in styles.scss throws an error on save

### ISSUE THREAD

**Issue by gedithejedi** [themefisher/bigspring-hugo-startup-theme#43]
Upon trying to save anything in this file i get this error

project\themes\bigspring\assets\scss\style.scss:

`(postcss) CssSyntaxError Unknown word (2:4)
  1 | // Color Variables
> 2 | {{ with site.Params.variables }}
    |    ^
  3 | $primary-color: {{.primary_color | default "#0AA8A7"}};
  4 | $text-color: {{.text_color | default "#777"}};
  5 | $text-color-dark: {{.text_color_dark | default "#222"}};`

thanks for the help

**Comment by tfsomrat** [comment]
Hello @gedithejedi 

I have checked this theme in my local machine, it works fine. can you tell me what have you changed after downloading the theme? and do you have any repository to share with me?
