### ISSUE TITLE
Differences in h1 between homepage and site pages

### ISSUE THREAD

**Issue by back2root** [themefisher/bigspring-hugo-startup-theme#9]
On the homepage the main heading `<h1>` has a different style than on the other site pages.
Compared to the homepage. the h1 attribute has the class _display-3_ attached on the site pages.

```html
<section class="section pb-0">
  <div class="container text-center">
    <h1 class="display-3">{{ .Title | markdownify }}</h1>
    {{ with .Params.subtitle }}
    <p>{{ . | markdownify }}</p>
    {{ end }}
  </div>
</section>
```

Is this by purpose or are you willing to accept a pull request to make the headings look the same?

**Comment by developer-evan** [comment]
Hello @back2root 

This is for theme look and feels purpose, we don't need a PR to change it, Thank you.

**Comment by abradshaw** [comment]
I agree with the OP - it looks inconsistent
